** BRANCH COMMIT **
Merging branches/HWRF_v3.4a into branches/HWRF, this includes
all the v3.4 updates to WPS.



git-svn-id: https://svn-wrf-wps.cgd.ucar.edu/branches/HWRF@700 86b71a92-4018-0410-97f8-d555beccfc3a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -119,6 +119,7 @@ if [ -n "$NETCDF" ] ; then
   echo "Will use NETCDF in dir: $NETCDF"
   # for 3.6.2 and greater there might be a second library, libnetcdff.a .  Check for this and use
   # if available
+  NETCDFF=" "
   if [ -f "$NETCDF/lib/libnetcdff.a" ] ; then
     NETCDFF="-lnetcdff"
   fi
@@ -152,3 +153,244 @@ fi
 # Found perl, so proceed with configuration
 perl arch/Config.pl -perl=$PERL -netcdf=$NETCDF -netcdff=$NETCDFF -os=$os -mach=$mach 
 
+
+#Checking cross-compiling capability for some particular environment 
+#on Linux and Mac box
+
+if [ $os = "Linux" -o $os = "Darwin" ]; then
+
+  SFC=`grep '^SFC' configure.wps | awk '{print $3}'`
+  SCC=`grep '^SCC' configure.wps | awk '{print $3}'`
+
+  SFC="`type $SFC 2>/dev/null | awk '{print $NF}' | sed -e 's/(//g;s/)//g'`"
+  SCC="`type $SCC 2>/dev/null | awk '{print $NF}' | sed -e 's/(//g;s/)//g'`"
+
+  if [ -e $NETCDF/lib/libnetcdf.a -a "$SFC" != "" -a "$SCC" != "" ]; then
+
+    SFC_MULTI_ABI=0
+    SCC_MULTI_ABI=0
+    CROSS_COMPILING=0
+
+    foo=foo_$$
+
+    echo
+    echo Testing for NetCDF, C and Fortran compiler
+    echo
+
+cat > ${foo}.c <<EOF 
+ int main(int argc, char ** argv)
+ {
+     return (0);
+ }
+EOF
+
+cat > ${foo}.f <<EOF
+          program test_exit
+            integer :: STATUS = 0
+            call EXIT(STATUS)
+          end program test_exit
+EOF
+
+    ar p $NETCDF/lib/libnetcdf.a nc.o > ${foo}.o
+    netcdf_arch="`file ${foo}.o | grep -o -E '[0-9]{2}-bit|i386'`"
+    rm ${foo}.o
+
+    $SFC -o ${foo} ${foo}.f > /dev/null 2>&1 
+    SFC_arch="`file ${foo} | grep -o -E '[0-9]{2}-bit|i386'`"
+    rm ${foo} ${foo}.o 2> /dev/null
+
+    $SCC -o ${foo} ${foo}.c > /dev/null 2>&1
+    SCC_arch="`file ${foo} | grep -o -E '[0-9]{2}-bit|i386'`"
+    rm ${foo} ${foo}.o 2> /dev/null
+
+    if [ "$SFC_arch" = "" -o "$SCC_arch" = "" ]; then
+      echo "  One of compilers testing failed!"
+      echo "  Please check your compiler"
+      echo 
+      rm -f ${foo} ${foo}.[cfo] 2> /dev/null
+      exit
+    else
+      cp configure.wps configure.wps.edit
+    fi
+
+    case $netcdf_arch in
+
+      32-bit|i386 )
+
+      if [ "$SFC_arch" = "64-bit" ] ; then
+        CROSS_COMPILING=1
+        $SFC -m32 -o ${foo} ${foo}.f > /dev/null 2>&1
+        if [ $? = 0 ]; then
+          SFC_MULTI_ABI=1
+          sed '/^SFC.*=/s/$/ -m32/' configure.wps.edit > configure.wps.tmp
+          mv configure.wps.tmp configure.wps.edit
+        fi
+      fi
+      if [ "$SCC_arch" = "64-bit" ] ; then
+        CROSS_COMPILING=1
+        $SCC -m32 -o ${foo} ${foo}.c > /dev/null 2>&1
+        if [ $? = 0 ]; then
+          SCC_MULTI_ABI=1
+          sed '/^SCC.*=/s/$/ -m32/' configure.wps.edit > configure.wps.tmp
+          mv configure.wps.tmp  configure.wps.edit
+        fi
+      fi
+
+      if [ $CROSS_COMPILING -eq 1 ] ; then
+        echo NOTE:
+        echo This installation NetCDF is 32-bit
+        if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" = "64-bit" \) \
+             -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" = "64-bit" \) ] ; then
+             rm configure.wps.edit
+             echo One of compilers is 64-bit and doesn\'t support cross-compiling.
+             echo Please check your NETCDF lib and compiler
+        else
+          echo -m32 is appended to configure.wps
+          echo It will be forced to build in 32-bit.
+          echo If you don\'t want 32-bit binaries, please use 64-bit NetCDF, and re-run the configure script.
+        fi
+      fi
+      ;;
+
+      64-bit )
+
+      if [ "$SFC_arch" = "32-bit" -o "$SFC_arch" = "i386" ] ; then
+        CROSS_COMPILING=1
+        $SFC -m64 -o ${foo} ${foo}.f > /dev/null 2>&1
+        if [ $? = 0 ]; then
+          SFC_MULTI_ABI=1
+          sed '/^SFC.*=/s/$/ -m64/' configure.wps.edit > configure.wps.tmp
+          mv configure.wps.tmp configure.wps.edit
+        fi
+      fi
+      if [ "$SCC_arch" = "32-bit" -o "$SCC_arch" = "i386" ] ; then
+        CROSS_COMPILING=1
+        $SCC -m64 -o ${foo} ${foo}.c > /dev/null 2>&1
+        if [ $? = 0 ]; then
+          SCC_MULTI_ABI=1
+          sed '/^SCC.*=/s/$/ -m64/' configure.wps.edit > configure.wps.tmp
+          mv configure.wps.tmp configure.wps.edit
+        fi
+      fi
+
+      if [ $CROSS_COMPILING -eq 1 ] ; then
+        echo NOTE:
+        echo This installation NetCDF is 64-bit
+        if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" != "64-bit" \) \
+            -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" != "64-bit" \) ]; then
+            rm configure.wps.edit
+            echo One of Compilers is 32-bit and doesn\'t support cross-compiling.
+            echo Please check your NetCDF lib and compiler
+        else
+          echo -m64 is appended to configure.wps
+          echo It will be forced to build in 64-bit. 
+          echo If you don\'t want 64-bit binaries, please use 32-bit NetCDF, and re-run the configure script.
+        fi
+      fi
+      ;;
+    esac
+    rm -f ${foo} ${foo}.[cfo] 2> /dev/null
+
+    if [ -e configure.wps.edit ]; then 
+      mv configure.wps.edit configure.wps
+    fi
+
+    if [ $CROSS_COMPILING -eq 0 ] ; then
+      echo This installation NetCDF is $netcdf_arch
+      echo C compiler is $SCC_arch
+      echo Fortran compiler is $SFC_arch
+    fi
+    echo
+
+    #  Does our Fortran work with the given NETCDF library.
+
+    if [ -f "fort_netcdf.f" ] ; then
+      /bin/rm fort_netcdf.f
+    fi
+    if [ -f "fort_netcdf" ] ; then
+      /bin/rm fort_netcdf
+    fi
+cat > fort_netcdf.f <<EOF 
+        program foo
+        include 'netcdf.inc'
+        integer ncid , status 
+        status = nf_open ( 'foo.nc' , 0 , ncid ) 
+        print *,'status = ',status
+        end program
+EOF
+    FFLAGS=`grep ^FFLAGS configure.wps | cut -d"=" -f2-`
+    cp $NETCDF/include/netcdf.inc .
+    FC=`grep ^SFC configure.wps | cut -d"=" -f2-`
+    $FC ${FFLAGS} fort_netcdf.f -o fort_netcdf -L${NETCDF}/lib -lnetcdf $NETCDFF > /dev/null 2>&1 
+    if [ -f "fort_netcdf" ] ; then
+      fort_netcdf > /dev/null 2>&1
+      if [ $? = 0 ]; then
+        /bin/rm fort_netcdf.f fort_netcdf netcdf.inc
+      else
+        echo
+        echo "Your Fortran + NETCDF did not run successfully."
+        echo
+      fi
+    else
+      echo
+      echo "Your versions of Fortran and NETCDF are not consistent."
+      echo
+    fi
+
+cat > c_test.c <<EOF
+#ifndef CRAY
+# ifdef NOUNDERSCORE
+#      define C_TEST c_test
+# else
+#   if defined ( F2CSTYLE ) || defined ( _DOUBLEUNDERSCORE )
+#      define C_TEST c_test__
+#   else
+#      define C_TEST c_test_
+#   endif
+# endif
+#endif
+#include <stdio.h>
+
+int C_TEST ( float *xx, int *ii )
+
+{
+ printf("OK print in C function.  \n" ) ;
+ printf("Values are xx = %5.2f and ii = %d \n", *xx, *ii ) ;
+ return(0) ;
+}
+EOF
+    CFLAGS=`grep ^CFLAGS configure.wps | cut -d"=" -f2-`
+    CPPFLAGS=`grep ^CPPFLAGS configure.wps | cut -d"=" -f2-`
+    CC=`grep ^SCC configure.wps | cut -d"=" -f2-`
+    ${CC} -c ${CFLAGS} ${CPPFLAGS} c_test.c
+
+cat > f_test.f90 <<EOF
+PROGRAM f_test
+   INTEGER :: ii
+   REAL    :: xx
+
+   ii = 1
+   xx = 2
+
+   CALL c_test ( xx , ii ) 
+
+END PROGRAM f_test
+EOF
+    $FC ${FFLAGS} f_test.f90 -o cf_test c_test.o > /dev/null 2>&1 
+    if [ -f "cf_test" ] ; then
+      cf_test > /dev/null 2>&1
+      if [ $? = 0 ]; then
+        /bin/rm -f cf_test c_test.c c_test.o f_test.f90 f_test.o
+      else
+        echo
+        echo "Your Fortran + C did not run successfully."
+        echo
+      fi
+    else
+      echo
+      echo "Your versions of Fortran and C are not consistent."
+      echo
+    fi
+
+  fi
+fi
